

services:
  db:
    image: postgres:16-alpine
    container_name: llm_postgres
    restart: always
    environment:
      POSTGRES_USER: otty
      POSTGRES_PASSWORD: 34561625Pph
      POSTGRES_DB: llm
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: llm_app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://otty:34561625Pph@db:5432/llm
    ports:
      - "8000:8000"

  alembic:
    build: .
    container_name: llm_alembic
    depends_on:
      - db
    command: alembic upgrade head
    volumes:
      - .:/app
    working_dir: /app
    environment:
      DATABASE_URL: postgresql+asyncpg://otty:34561625Pph@db:5432/llm

volumes:
  pgdata:
