

services:
  db:
    image: postgres:16-alpine
    container_name: llm_postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: llm_app
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./Frontend/llm_frontend
      dockerfile: Dockerfile
    container_name: llm_frontend
    depends_on:
      - app
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend/llm_frontend:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      NODE_ENV: development
      BACKEND_URL: http://app:8000
      PORT: 3000
      NEXT_PUBLIC_API_URL: http://localhost:8000 

volumes:
  pgdata:
