

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: llm_app
  
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    env_file:
      - .env
    environment:
      
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    expose:
      - "8000"

  frontend:
    build:
      context: ./Frontend/llm_frontend
      dockerfile: Dockerfile
    container_name: llm_frontend
    depends_on:
      - app
    env_file:
      - .env
    environment:
      NODE_ENV: production
      
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      PORT: 3000
    expose:
      - "3000"
