version: '3.8'

services:
  app:
    image: coderph/llm-app:latest
    container_name: llm_app

    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    environment:
     
      DATABASE_URL: ${DATABASE_URL}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    expose:
      - "8000"

  frontend:
    image: coderph/llm-frontend:latest
    container_name: llm_frontend
    depends_on:
      - app
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      PORT: 3000
    expose:
      - "3000"

