"""fix: add query_history table

Revision ID: 16bac1216cb9
Revises: 4c92f077094e
Create Date: 2025-07-31 20:02:08.755047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16bac1216cb9'
down_revision: Union[str, Sequence[str], None] = '4c92f077094e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_hist',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('query_id', sa.String(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('query_id')
    )
    op.create_index(op.f('ix_query_hist_id'), 'query_hist', ['id'], unique=False)
    op.create_index(op.f('ix_query_hist_user_id'), 'query_hist', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_query_hist_user_id'), table_name='query_hist')
    op.drop_index(op.f('ix_query_hist_id'), table_name='query_hist')
    op.drop_table('query_hist')
    # ### end Alembic commands ###
